name: apertium-spa-cat CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    call-workflow:
    uses: apertium/github-actions/.github/workflows/bilingual-build.yml@master